### ISSUE TITLE
Get the differences from one side instead of both?

### ISSUE THREAD

**Issue by Pikachews** [weichch/system-text-json-jsondiffpatch#34]
Is there a way to get the different between `left` and `right` but only returning the field of one side?
e.g.
```
A = {
    changedField: "value1",
    unchangedField: "test"
}

B = {
    changedField: "value2",
    unchangedField: "test"
}

A.Diff(B) = {
    changedField: "value2"
}
```

**Comment by weichch** [comment]
By default the diff is generated in `jsondiffpatch` format which has both old and new values when property value changes. 

You can implement your own formatter to convert the default delta into any format. One built-in example is [`JsonPatchDeltaFormatter`](https://github.com/weichch/system-text-json-jsondiffpatch/blob/62deb286b7534f4054810f68ad8f5f55ffce974c/src/SystemTextJson.JsonDiffPatch/Diffs/Formatters/JsonPatchDeltaFormatter.cs).
