### ISSUE TITLE
Add a THIRD-PARTY-NOTICES.txt

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [weichch/system-text-json-jsondiffpatch#40]
Hi there,

I noticed that you included code from https://github.com/google/diff-match-patch and added its license file. From the repository root however it looks like everything under it is MIT. The same goes for the NuGet package which does not include the license file of the third party component. It is pretty common to simply create a file `THIRD-PARTY-NOTICES.txt` and list all used components, their licenses, copyrights and version numbers. I already prepared a PR for you at #41.

Best regards,
Georg

**Comment by weichch** [comment]
Thanks for raising the issue.

I do have their License included at [this path](https://github.com/weichch/system-text-json-jsondiffpatch/blob/592940e5a6c7510128b81bb9bedd6cc729805441/src/SystemTextJson.JsonDiffPatch/Diffs/DiffMatchPatch/LICENSE) in the source code.

The license however is not included in the NuGet package at the moment, and I'm happy to be advised if it should be included?

**Comment by weichch** [comment]
Thanks for contributing. I have merged the PR and will include the notice file in next release.
